#!/bin/bash

# when receive a ctrl + c signal
trap "exit" 2

exit()
{
 ps -ef | grep python | cut -c 9-15| xargs kill -s 9
} 
ps -ef | grep python | cut -c 9-15| xargs kill -s 9

  python ~/5GCORE/AMF/Namf_Communication/__init__.py \
& python ~/5GCORE/SMF/Nsmf_PDUSession/__init__.py \
& python ~/5GCORE/AUSF/__init__.py \
& python ~/5GCORE/UPF/__init__.py \
& python ~/5GCORE/UDM/Nudm_UEAuthentication/__init__.py
